// Build step: embed the Python SDK's price table (refreshed from LiteLLM by
// sdk/scripts/update_prices.py) so both SDKs price model calls identically.
import { readFileSync, writeFileSync } from "node:fs";

const table = JSON.parse(readFileSync(new URL("../../sdk/agentfences/prices.json", import.meta.url), "utf8"));
writeFileSync(new URL("../src/prices.generated.ts", import.meta.url),
  `// Generated by scripts/prices.mjs from sdk/agentfences/prices.json. Do not edit.\n` +
  `// ${table.source}, fetched ${table.fetched}\n` +
  `export const PRICES: Record<string, PriceEntry> = ${JSON.stringify(table.models)};\n` +
  `export interface Rates { in: number; out: number; cache_read?: number; cache_write?: number }\n` +
  `export interface PriceEntry extends Rates { above?: number; tier?: Rates }\n`);
console.log(`prices: ${Object.keys(table.models).length} models`);
